name: "Samsung Frame TV Art Changer"
description: "Automatically downloads and displays artwork on your Samsung Frame TV from Google Art, Bing Wallpapers, or your local media folder."
version: "1.6.3"
url: "https://github.com/adamwarniment/homeassistant-addons"
slug: "hass-frametv-artchanger"
init: false
startup: once
boot: manual
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "media:rw"
  - "addons:rw"
  - "share:rw"
options:
  tv: "192.168.1.1"
  google_art: true
  download_high_res: true
  bing_wallpapers: false
  media_folder: false
  media_folder_path: "/media/frame"
  same_image: false
  matte: none
  matte_color: black
  log_path: '/addons/frame/uploaded_files.json'
schema:
  tv: "str?"
  google_art: "bool?"
  download_high_res: "bool?"
  bing_wallpapers: "bool?"
  media_folder: "bool?"
  media_folder_path: "str?"
  same_image: "bool?"
  matte: list(none|myshelf|modernthin|modern|modernwide|flexible|shadowbox|panoramic|triptych|mix|squares)?
  matte_color: list(black|neutral|antique|warm|polar|sand|seafoam|sage|burgandy|navy|apricot|byzantine|lavender|redorange|skyblue|turquoise)?
  log_path: "str?"
image: adamwarniment/{arch}-addon-homeassistant-samsung-frametv-artchanger